services:
  postgres:
    image: postgres:17.4
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: confidentiality_system
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
      - ./internal/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  neo4j:
    image: neo4j:2025.03.0
    container_name: neo4j_db
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/mypassword
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7.4.2
    container_name: redis_db
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  neo4j_data:
  redis_data:
